import type { BrowseRead } from "../../shared/browse";
import type { SymbolSearch } from "../../shared/symbols";
import type { BrowseApi } from "./browse";

/** Ctags provides declarations, not semantic type or import resolution. */
export async function findDefinitions(
  api: BrowseApi,
  file: BrowseRead,
  name: string,
  signal: AbortSignal,
): Promise<SymbolSearch> {
  if (!api.symbols) throw new Error("Symbol search is unavailable.");
  const local = await api.symbols(
    file.source,
    name,
    { path: file.path, identity: file.identity },
    signal,
  );
  signal.throwIfAborted();
  if (local.identity !== file.identity)
    throw new Error("This file changed. Refresh it before going to a definition.");
  const exact = (result: SymbolSearch) => ({
    ...result,
    matches: result.matches.filter((match) => match.name === name),
  });
  const result = exact(local);
  if (result.matches.length || local.unavailable?.includes("file changed")) return result;
  // The project index is generated by Universal Ctags and tied to a commit.
  const project = await api.symbols(file.source, name, {}, signal);
  signal.throwIfAborted();
  return exact(project);
}
